---
- name: Deploy Prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

- name: Deploy Grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    ports:
      - "3000:3000"
