---
- name: Pull GitLab CE image
  docker_image:
    name: gitlab/gitlab-ce
    tag: latest
    source: pull

- name: Run GitLab container
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce:latest
    state: started
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
